# Generated by Django 5.2.5 on 2025-09-02 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('profile_image', models.CharField()),
                ('profile_image_id', models.CharField()),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField()),
                ('order', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snap_stream_app.post')),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snap_stream_app.user'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snap_stream_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snap_stream_app.user')),
            ],
            options={
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='snap_stream_app.user')),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to='snap_stream_app.user')),
            ],
            options={
                'db_table': 'follow_relation',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snap_stream_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snap_stream_app.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
