# Generated by Django 5.2.5 on 2025-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_stream_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_id',
            field=models.CharField(null=True),
        ),
    ]
