# Generated by Django 5.2.5 on 2025-09-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap_stream_app', '0002_alter_post_options_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
